official_countries = \
    {'AD': 'Andorra',
     'AE': 'United Arab Emirates',
     'AF': 'Afghanistan',
     'AG': 'Antigua and Barbuda',
     'AI': 'Anguilla',
     'AL': 'Albania',
     'AM': 'Armenia',
     'AO': 'Angola',
     'AQ': 'Antarctica',
     'AR': 'Argentina',
     'AS': 'American Samoa',
     'AT': 'Austria',
     'AU': 'Australia',
     'AW': 'Aruba',
     'AX': 'Åland Islands',
     'AZ': 'Azerbaijan',
     'BA': 'Bosnia',
     'BB': 'Barbados',
     'BD': 'Bangladesh',
     'BE': 'Belgium',
     'BF': 'Burkina Faso',
     'BG': 'Bulgaria',
     'BH': 'Bahrain',
     'BI': 'Burundi',
     'BJ': 'Benin',
     'BL': 'Saint Barthélemy',
     'BM': 'Bermuda',
     'BN': 'Brunei Darussalam',
     'BO': 'Bolivia (Plurinational State of)',
     'BQ': 'Bonaire, Sint Eustatius and Saba',
     'BR': 'Brazil',
     'BS': 'Bahamas',
     'BT': 'Bhutan',
     'BV': 'Bouvet Island',
     'BW': 'Botswana',
     'BY': 'Belarus',
     'BZ': 'Belize',
     'CA': 'Canada',
     'CC': 'Cocos (Keeling) Islands',
     'CD': 'Congo, Democratic Republic of the',
     'CF': 'Central African Republic',
     'CG': 'Congo',
     'CH': 'Switzerland',
     'CI': 'Côte d\'Ivoire',
     'CK': 'Cook Islands',
     'CL': 'Chile',
     'CM': 'Cameroon',
     'CN': 'China',
     'CO': 'Colombia',
     'CR': 'Costa Rica',
     'CU': 'Cuba',
     'CV': 'Cabo Verde',
     'CW': 'Curaçao',
     'CX': 'Christmas Island',
     'CY': 'Cyprus',
     'CZ': 'Czechia',
     'DE': 'Germany',
     'DJ': 'Djibouti',
     'DK': 'Denmark',
     'DM': 'Dominica',
     'DO': 'Dominican Republic',
     'DZ': 'Algeria',
     'EC': 'Ecuador',
     'EE': 'Estonia',
     'EG': 'Egypt',
     'EH': 'Western Sahara',
     'ER': 'Eritrea',
     'ES': 'Spain',
     'ET': 'Ethiopia',
     'FI': 'Finland',
     'FJ': 'Fiji',
     'FK': 'Falkland Islands (Malvinas)',
     'FM': 'Micronesia (Federated States of)',
     'FO': 'Faroe Islands',
     'FR': 'France',
     'GA': 'Gabon',
     'GB': 'United Kingdom of Great Britain and Northern Ireland',
     'GD': 'Grenada',
     'GE': 'Georgia',
     'GF': 'French Guiana',
     'GG': 'Guernsey',
     'GH': 'Ghana',
     'GI': 'Gibraltar',
     'GL': 'Greenland',
     'GM': 'Gambia',
     'GN': 'Guinea',
     'GP': 'Guadeloupe',
     'GQ': 'Equatorial Guinea',
     'GR': 'Greece',
     'GS': 'South Georgia and the South Sandwich Islands',
     'GT': 'Guatemala',
     'GU': 'Guam',
     'GW': 'Guinea-Bissau',
     'GY': 'Guyana',
     'HK': 'Hong Kong',
     'HM': 'Heard Island and McDonald Islands',
     'HN': 'Honduras',
     'HR': 'Croatia',
     'HT': 'Haiti',
     'HU': 'Haiti',
     'ID': 'Indonesia',
     'IE': 'Ireland',
     'IL': 'Israel',
     'IM': 'Isle of Man',
     'IN': 'India',
     'IO': 'British Indian Ocean Territory',
     'IQ': 'Iraq',
     'IR': 'Iran (Islamic Republic of)',
     'IS': 'Iceland',
     'IT': 'Italy',
     'JE': 'Jersey',
     'JM': 'Jamaica',
     'JO': 'Jordan',
     'JP': 'Japan',
     'KE': 'Kenya',
     'KG': 'Kyrgyzstan',
     'KH': 'Cambodia',
     'KI': 'Kiribati',
     'KM': 'Comoros',
     'KN': 'Saint Kitts and Nevis',
     'KP': 'Korea (Democratic People\'s Republic of)',
     'KR': 'Korea, Republic of',
     'KW': 'Kuwait',
     'KY': 'Cayman Islands',
     'KZ': 'Kazakhstan',
     'LA': 'Lao People\'s Democratic Republic',
     'LB': 'Lebanon',
     'LC': 'Saint Lucia',
     'LI': 'Liechtenstein',
     'LK': 'Sri Lanka',
     'LR': 'Liberia',
     'LS': 'Lesotho',
     'LT': 'Lithuania',
     'LU': 'Luxembourg',
     'LV': 'Latvia',
     'LY': 'Libya',
     'MA': 'Morocco',
     'MC': 'Monaco',
     'MD': 'Moldova, Republic of',
     'ME': 'Montenegro',
     'MF': 'Saint Martin (French part)',
     'MG': 'Madagascar',
     'MH': 'Marshall Islands',
     'MK': 'North Macedonia',
     'ML': 'Mali',
     'MM': 'Myanmar',
     'MN': 'Mongolia',
     'MO': 'Macao',
     'MP': 'Northern Mariana Islands',
     'MQ': 'Martinique',
     'MR': 'Mauritania',
     'MS': 'Montserrat',
     'MT': 'Malta',
     'MU': 'Mauritius',
     'MV': 'Maldives',
     'MW': 'Malawi',
     'MX': 'Mexico',
     'MY': 'Malaysia',
     'MZ': 'Mozambique',
     'NA': 'Namibia',
     'NC': 'New Caledonia',
     'NE': 'Niger',
     'NF': 'Norfolk Island',
     'NG': 'Nigeria',
     'NI': 'Nicaragua',
     'NL': 'Netherlands',
     'NO': 'Norway',
     'NP': 'Nepal',
     'NR': 'Nauru',
     'NU': 'Niue',
     'NZ': 'New Zealand',
     'OM': 'Oman',
     'PA': 'Panama',
     'PE': 'Peru',
     'PF': 'French Polynesia',
     'PG': 'Papua New Guinea',
     'PH': 'Philippines',
     'PK': 'Pakistan',
     'PL': 'Poland',
     'PM': 'Saint Pierre and Miquelon',
     'PN': 'Pitcairn',
     'PR': 'Puerto Rico',
     'PS': 'Palestine, State of',
     'PT': 'Portugal',
     'PW': 'Palau',
     'PY': 'Paraguay',
     'QA': 'Qatar',
     'RE': 'Réunion',
     'RO': 'Romania',
     'RS': 'Serbia',
     'RU': 'Russian Federation',
     'RW': 'Rwanda',
     'SA': 'Saudi Arabia',
     'SB': 'Solomon Islands',
     'SC': 'Seychelles',
     'SD': 'Sudan',
     'SE': 'Sweden',
     'SG': 'Singapore',
     'SH': 'Saint Helena, Ascension and Tristan da Cunha',
     'SI': 'Slovenia',
     'SJ': 'Svalbard and Jan Mayen',
     'SK': 'Slovakia',
     'SL': 'Sierra Leone',
     'SM': 'San Marino',
     'SN': 'Senegal',
     'SO': 'Somalia',
     'SR': 'Suriname',
     'SS': 'South Sudan',
     'ST': 'Sao Tome and Principe',
     'SV': 'El Salvador',
     'SX': 'Sint Maarten (Dutch part)',
     'SY': 'Syrian Arab Republic',
     'SZ': 'Eswatini',
     'TC': 'Turks and Caicos Islands',
     'TD': 'Chad',
     'TF': 'French Southern Territories',
     'TG': 'Togo',
     'TH': 'Thailand',
     'TJ': 'Tajikistan',
     'TK': 'Tokelau',
     'TL': 'Timor-Leste',
     'TM': 'Turkmenistan',
     'TN': 'Tunisia',
     'TO': 'Tonga',
     'TR': 'Turkey',
     'TT': 'Trinidad and Tobago',
     'TV': 'Tuvalu',
     'TW': 'Taiwan, Province of China',
     'TZ': 'Tanzania, United Republic of',
     'UA': 'Ukraine',
     'UG': 'Uganda',
     'UM': 'United States Minor Outlying Islands',
     'US': 'United States of America',
     'UY': 'Uruguay',
     'UZ': 'Uzbekistan',
     'VA': 'Holy See',
     'VC': 'Saint Vincent and the Grenadines',
     'VE': 'Venezuela (Bolivarian Republic of)',
     'VG': 'Virgin Islands (British)',
     'VI': 'Virgin Islands (U.S.)',
     'VN': 'Viet Nam',
     'VU': 'Vanuatu',
     'WF': 'Wallis and Futuna',
     'WS': 'Samoa',
     'YE': 'Yemen',
     'YT': 'Mayotte',
     'ZA': 'South Africa',
     'ZM': 'Zambia',
     'ZW': 'Zimbabwe'
     }

user_countries = \
    {'QM': 'United States of America',
     'QO': 'Outlying Oceania',
     'QZ': 'Community Plant Variety Office',
     'XA': 'Canary Islands',
     'XI': 'Northern Ireland',
     'XK': 'Kosovo',
     'XN': 'Nordic Patent Institute',
     'XU': 'International Union for the Protection of New Varieties of Plants',
     'XV': 'Visegrad Patent Institute',
     'XX': 'Unknown State',
     'XZ': 'International Waters',
     'ZZ': 'United States of America or Unknown Territory'}

reserved_countries = \
    {'AC': 'Ascension Island',
     'CP': 'Clipperton Island',
     'CQ': 'Island of Sark',
     'DG': 'Diego Garcia',
     'EA': 'Ceuta, Melilla',
     'EU': 'European Union',
     'EZ': 'Eurozone',
     'FX': 'France, Metropolitan',
     'IC': 'Canary Islands',
     'SU': 'USSR',
     'TA': 'Tristan da Cunha',
     'UK': 'United Kingdom',
     'UN': 'United Nations'}

transitional_countries = \
    {'AN': 'Netherlands Antilles',
     'BU': 'Burma',
     'CS': 'Czechoslovakia',
     'NT': 'Neutral Zone',
     'SF': 'Finland',
     'TP': 'East Timor',
     'YU': 'Yugoslavia',
     'ZR': 'Zaire'}

indeterminate_countries = \
    {'DY': 'Benin',
     'EW': 'Estonia',
     'FL': 'Liechtenstein',
     'JA': 'Jamaica',
     'LF': 'Libya Fezzan',
     'PI': 'Philippines',
     'RA': 'Argentina',
     'RB': 'Bolivia or Botswana',
     'RC': 'China',
     'RH': 'Haiti',
     'RI': 'Indonesia',
     'RL': 'Lebanon',
     'RM': 'Madagascar',
     'RN': 'Niger',
     'RP': 'Philippines',
     'SF': 'Finland',
     'WG': 'Grenada',
     'WL': 'Saint Lucia',
     'WV': 'Saint Vincent',
     'YV': 'Venezuela',
     'LT': 'Libya Tripoli',
     'ME': 'Western Sahara',
     'RU': 'Burundi'}

unused_countries = \
    {'AP': 'African Regional Industrial Property Organization',
     'BX': 'Benelux Trademarks and Designs Office',
     'EF': 'Union of Countries under the European Community Patent Convention',
     'EM': 'European Trademark Office',
     'EP': 'European Patent Organization',
     'EV': 'Eurasian Patent Organization',
     'GC': 'Patent Office of the Cooperation Council for the Arab States of the Gulf',
     'IB': 'International Bureau of WIPO',
     'OA': 'African Intellectual Property Organization',
     'WO': 'World Intellectual Property Organization'}

deleted_countries = \
    {'AI': 'French Afars and Issas',
     'BQ': 'British Antarctic Territory',
     'CT': 'Canton and Enderbury Islands',
     'DD': 'German Democratic Republic',
     'DY': 'Dahomey',
     'FQ': 'French Southern and Antarctic Territories',
     'GE': 'Gilbert Islands',
     'HV': 'Upper Volta',
     'JT': 'Johnston Island',
     'MI': 'Midway Islands',
     'NH': 'New Hebrides',
     'NQ': 'Dronning Maud Land',
     'PC': 'Pacific Islands (Trust Territory)',
     'PU': 'United States Miscellaneous Pacific Islands',
     'PZ': 'Panama Canal Zone',
     'RH': 'Southern Rhodesia',
     'SK': 'Sikkim',
     'VD': 'Viet-Nam, Democratic Republic of',
     'WK': 'Wake Island',
     'YD': 'Yemen, Democratic'}


def get_official_country(x, y=None):
    if y is None:
        y = dict(official_countries)
    try:
        return y[x]
    except IndexError:
        return None


def get_official_code(x, y):
    try:
        return x[y]
    except KeyError:
        return None


def letter_parser(x):
    z = ''
    for y in x:
        letters = {'🇦': 'a', '🇧': 'b', '🇨': 'c', '🇩': 'd', '🇪': 'e', '🇫': 'f', '🇬': 'g', '🇭': 'h', '🇮': 'i',  '🇯': 'j',
                   '🇰': 'k', '🇱': 'l', '🇲': 'm', '🇳': 'n', '🇴': 'o', '🇵': 'p', '🇶': 'q', '🇷': 'r', '🇸': 's', '🇹': 't',
                   '🇺': 'u', '🇻': 'v', '🇼': 'w', '🇽': 'x', '🇾': 'y', '🇿': 'z'}
        z += letters[y]
    return z
